### ISSUE TITLE
🐛 Wrong scheme group version defined in register.go

### ISSUE THREAD

**Issue by tobiasgiese** [projectcalico/api#32]
Currently it's not possible to work with Kubernetes resources as the scheme is added with the wrong version `v3`.

https://github.com/projectcalico/api/blob/36fbcf68f1c87cd15dd7f007cb26e9bc9035d50a/pkg/apis/projectcalico/v3/register.go#L15

Further, the following error message occurs

```
no matches for kind "GlobalNetworkPolicy" in version "projectcalico.org/v3"
```

## Expected Behavior

The correct version `v1` should be added.

## Possible Solution

Adjust the schemes version as in the PR of the legacy API https://github.com/projectcalico/libcalico-go/pull/1431

## Your Environment

* calico version:
* Operating System and version:
* Link to your project (optional):

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by tobiasgiese** [comment]
Or am I doing something wrong?

What's not working is

```go
_ = calicov3.AddToScheme(scheme.Scheme)
```

And the workaround is

```go
schemeGroupVersion := schema.GroupVersion{
	Group:   "crd.projectcalico.org",
	Version: "v1",
}
scheme.Scheme.AddKnownTypes(schemeGroupVersion, &calicov3.GlobalNetworkPolicy{}, &calicov3.GlobalNetworkPolicyList{})

metav1.AddToGroupVersion(scheme.Scheme, schemeGroupVersion)
```

**Comment by caseydavenport** [comment]
@tobiasgiese really sorry I missed this one! Just slipped under my radar. I don't think that adding crd.projectcalico.org/v1 is the right thing, though.

The APIs in this repository need the API server to run - see https://docs.projectcalico.org/maintenance/install-apiserver

the crd.projectcalico.org/v1 API is an internal-only API that just happens to look exactly like the public one in many ways :facepalm:

**Comment by salem017** [comment]
Yes but in our side, the script deploy some global network policies which are only available in crd.projectcalico.org/v1 (with only the version modification : `the server could not find the requested resource (get networkpolicies.projectcalico.org)`). Thanks to this modification, the script create the right ressources

**Comment by caseydavenport** [comment]
> the script deploy some global network policies which are only available in crd.projectcalico.org/v1 (

@salem017 As per my comment, you need to install the API server. That will make them available in the projectcalico.org/v3 group+version.

Do not use the `crd.projectcalico.org` API group, we don't support using that directly.

**Comment by caseydavenport** [comment]
To state it a bit more strongly, using the `crd.projectcalico.org` API group bypasses defaulting and validation and should not be used - it has a high likelihood to break your cluster in ways that are hard to diagnose.

You should install the API server and use the `projectcalico.org/v3` API group, which is what this repository is intended for.
