### ISSUE TITLE
The demo main.go of example/list-gnp

### ISSUE THREAD

**Issue by JING21** [projectcalico/api#60]
The demo code use package "github.com/projectcalico/api/pkg/client/clientset_generated/clientset" to create a client .Then it use ProjectcalicoV3() to get calico resources. The result code  is a error panic : panic: the server could not find the requested resource (get globalnetworkpolicies.projectcalico.org).  The client uses group and version is projectcalico.org/v3, but the api-resources in the cluster is crd.projectcalico.org/v1.
## Expected Behavior

The demo code ande clientset should get the calciao resources?

## Current Behavior

Got a panic error instead of getting list result

## Steps to Reproduce (for bugs)

1.use a kubeconfig to build the client and run the code

## Context

 Is there any client can directly get the api-resources from kubernetes cluster?
## Your Environment

* calico version: v3.23.0
* Operating System and version: Centos7
* Kubernetes version: 1.21.5
* client-go version: v0.23.2	
* projectcalico/api  v0.0.0-20220505235232-ce7a5122e146
* k8s.io/apimachinery v0.24.0 
* Link to your project (optional):
The api-version is shown in the capture.
![image](https://user-images.githubusercontent.com/31011622/168967405-1d528a4c-1b43-4861-ab76-60c164f67e5d.png)

**Comment by cmssczy** [comment]
Do you have solved this problem?
I also had the same problem with k8s v1.23.3 and calico v3.21.4

**Comment by mpiexec** [comment]
> The client uses group and version is projectcalico.org/v3, but the api-resources in the cluster is crd.projectcalico.org/v1

I could get resources with such a patch:

```diff
~> diff -u pkg/apis/projectcalico/v3/register.go{,.orig}
--- pkg/apis/projectcalico/v3/register.go       2023-04-18 09:13:22.000000000 +0300
+++ pkg/apis/projectcalico/v3/register.go.orig  2023-04-18 09:13:11.000000000 +0300
@@ -9,10 +9,10 @@
 )

 // GroupName is the group name use in this package
-const GroupName = "crd.projectcalico.org"
+const GroupName = "projectcalico.org"

 // SchemeGroupVersion is group version used to register these objects
-var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1"}
+var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v3"}
 var SchemeGroupVersionInternal = schema.GroupVersion{Group: GroupName, Version: runtime.APIVersionInternal}
 ```

**Comment by promacanthus** [comment]
> > The client uses group and version is projectcalico.org/v3, but the api-resources in the cluster is crd.projectcalico.org/v1
> 
> I could get resources with such a patch:
> 
> ```diff
> ~> diff -u pkg/apis/projectcalico/v3/register.go{.orig,}
> --- pkg/apis/projectcalico/v3/register.go.orig  2023-04-18 09:13:11.000000000 +0300
> +++ pkg/apis/projectcalico/v3/register.go       2023-04-18 09:13:22.000000000 +0300
> @@ -9,10 +9,10 @@
>  )
> 
>  // GroupName is the group name use in this package
> -const GroupName = "projectcalico.org"
> +const GroupName = "crd.projectcalico.org"
> 
>  // SchemeGroupVersion is group version used to register these objects
> -var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v3"}
> +var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1"}
>  var SchemeGroupVersionInternal = schema.GroupVersion{Group: GroupName, Version: runtime.APIVersionInternal}
> ```

Hardcoding may not be an elegant solution.

**Comment by promacanthus** [comment]
error message may be like this: `failed to determine if *v3.BGPConfiguration is namespaced: failed to get restmapping: failed to find API group \"projectcalico.org\"`.

As an example, using calico v3.27.0,  you can follow the steps below to resolve this issue.

```
# 1. Install the `crd.projectcalico.org/v1` crds: 
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/crds.yaml

# 2. Install the calico api-server: 
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/apiserver.yaml

# 3. Generate a private key and CA bundle: 
openssl req -x509 -nodes -newkey rsa:4096 -keyout apiserver.key -out apiserver.crt -days 365 -subj "/" -addext "subjectAltName = DNS:calico-api.calico-apiserver.svc"

# 4. Provide the key and certificate to the Calico API server as a Kubernetes secret: `kubectl create secret -n calico-apiserver generic calico-apiserver-certs --from-file=apiserver.key --from-file=apiserver.crt

# 5. Configure the main API server with the CA bundle: 
kubectl patch apiservice v3.projectcalico.org -p "{\"spec\": {\"caBundle\": \"$(kubectl get secret -n calico-apiserver calico-apiserver-certs -o go-template='{{ index .data "apiserver.crt" }}')\"}}"
```

For more details, read [Enable kubectl to manage Calico APIs](https://docs.tigera.io/calico/latest/operations/install-apiserver)

Show api-resources in the cluster:
```
kubectl api-resources --api-group crd.projectcalico.org
NAME                            SHORTNAMES   APIVERSION                 NAMESPACED   KIND
bgpconfigurations                            crd.projectcalico.org/v1   false        BGPConfiguration
bgpfilters                                   crd.projectcalico.org/v1   false        BGPFilter
bgppeers                                     crd.projectcalico.org/v1   false        BGPPeer
blockaffinities                              crd.projectcalico.org/v1   false        BlockAffinity
caliconodestatuses                           crd.projectcalico.org/v1   false        CalicoNodeStatus
clusterinformations                          crd.projectcalico.org/v1   false        ClusterInformation
felixconfigurations                          crd.projectcalico.org/v1   false        FelixConfiguration
globalnetworkpolicies                        crd.projectcalico.org/v1   false        GlobalNetworkPolicy
globalnetworksets                            crd.projectcalico.org/v1   false        GlobalNetworkSet
hostendpoints                                crd.projectcalico.org/v1   false        HostEndpoint
ipamblocks                                   crd.projectcalico.org/v1   false        IPAMBlock
ipamconfigs                                  crd.projectcalico.org/v1   false        IPAMConfig
ipamhandles                                  crd.projectcalico.org/v1   false        IPAMHandle
ippools                                      crd.projectcalico.org/v1   false        IPPool
ipreservations                               crd.projectcalico.org/v1   false        IPReservation
kubecontrollersconfigurations                crd.projectcalico.org/v1   false        KubeControllersConfiguration
networkpolicies                              crd.projectcalico.org/v1   true         NetworkPolicy
networksets                                  crd.projectcalico.org/v1   true         NetworkSet
```

```
kubectl api-resources --api-group projectcalico.org    
NAME                            SHORTNAMES                                      APIVERSION             NAMESPACED   KIND
bgpconfigurations               bgpconfig,bgpconfigs                            projectcalico.org/v3   false        BGPConfiguration
bgpfilters                                                                      projectcalico.org/v3   false        BGPFilter
bgppeers                                                                        projectcalico.org/v3   false        BGPPeer
blockaffinities                 blockaffinity,affinity,affinities               projectcalico.org/v3   false        BlockAffinity
caliconodestatuses              caliconodestatus                                projectcalico.org/v3   false        CalicoNodeStatus
clusterinformations             clusterinfo                                     projectcalico.org/v3   false        ClusterInformation
felixconfigurations             felixconfig,felixconfigs                        projectcalico.org/v3   false        FelixConfiguration
globalnetworkpolicies           gnp,cgnp,calicoglobalnetworkpolicies            projectcalico.org/v3   false        GlobalNetworkPolicy
globalnetworksets                                                               projectcalico.org/v3   false        GlobalNetworkSet
hostendpoints                   hep,heps                                        projectcalico.org/v3   false        HostEndpoint
ipamconfigurations              ipamconfig                                      projectcalico.org/v3   false        IPAMConfiguration
ippools                                                                         projectcalico.org/v3   false        IPPool
ipreservations                                                                  projectcalico.org/v3   false        IPReservation
kubecontrollersconfigurations                                                   projectcalico.org/v3   false        KubeControllersConfiguration
networkpolicies                 cnp,caliconetworkpolicy,caliconetworkpolicies   projectcalico.org/v3   true         NetworkPolicy
networksets                     netsets                                         projectcalico.org/v3   true         NetworkSet
profiles                                                                        projectcalico.org/v3   false        Profile
```

From the above output, it can be seen that both the v1 and v3 CRDs have been successfully installed.

**Comment by tmjd** [comment]
No one should be expecting to interact with the crd.projectcalico.org resources. The calico-apiserver is necessary to interact with the projectcalico.org resources and this API library is built to interact with the projectcalico.org resources exposed by the calico-apiserver.
If the calico-apiserver is not available (like prior to installation) then the calicoctl utility is available to create Calico resources.

The reason for this is that there is validation that needs to be performed before creating crd.projectcalico.org resources, calico-apiserver and calicoctl will perform that validation, editing the crd.projectcalico.org resources bypasses that validation.

**Comment by caseydavenport** [comment]
xref: https://github.com/projectcalico/calico/issues/6412

**Comment by matthewdupre** [comment]
I'd also strongly recommend using the operator installation process if possible.  It sets up a fully configured environment including the apiserver where this should all work out of the box without requiring carefully maintaining an install script.
